# Dependabot configuration for melos multipackage workspace
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Workspace root
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      
  # Core package
  - package-ecosystem: "pub"  
    directory: "/packages/pacors_core"
    schedule:
      interval: "weekly"
      
  # Auth package
  - package-ecosystem: "pub"
    directory: "/packages/pacors_solid_auth" 
    schedule:
      interval: "weekly"
      
  # UI package
  - package-ecosystem: "pub"
    directory: "/packages/pacors_ui"
    schedule:
      interval: "weekly"
